//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.18 at 03:06:16 PM CDT 
//


package com.ylc.peer.assignnum.response.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HDR">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="MESSAGE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RESP">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="FORWARD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ACCEPTED" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hdr",
    "resp"
})
@XmlRootElement(name = "PEER")
public class PEER {

    @XmlElement(name = "HDR", required = true)
    protected PEER.HDR hdr;
    @XmlElement(name = "RESP", required = true)
    protected PEER.RESP resp;

    /**
     * Gets the value of the hdr property.
     * 
     * @return
     *     possible object is
     *     {@link PEER.HDR }
     *     
     */
    public PEER.HDR getHDR() {
        return hdr;
    }

    /**
     * Sets the value of the hdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link PEER.HDR }
     *     
     */
    public void setHDR(PEER.HDR value) {
        this.hdr = value;
    }

    /**
     * Gets the value of the resp property.
     * 
     * @return
     *     possible object is
     *     {@link PEER.RESP }
     *     
     */
    public PEER.RESP getRESP() {
        return resp;
    }

    /**
     * Sets the value of the resp property.
     * 
     * @param value
     *     allowed object is
     *     {@link PEER.RESP }
     *     
     */
    public void setRESP(PEER.RESP value) {
        this.resp = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="MESSAGE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "status",
        "message"
    })
    public static class HDR {

        @XmlElement(name = "STATUS", required = true)
        protected String status;
        @XmlElement(name = "MESSAGE", required = true)
        protected String message;

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSTATUS() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSTATUS(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the message property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMESSAGE() {
            return message;
        }

        /**
         * Sets the value of the message property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMESSAGE(String value) {
            this.message = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="FORWARD" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ACCEPTED" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "did",
        "forward",
        "accepted"
    })
    public static class RESP {

        @XmlElement(name = "DID", required = true)
        protected String did;
        @XmlElement(name = "FORWARD", required = true)
        protected String forward;
        @XmlElement(name = "ACCEPTED", required = true)
        protected String accepted;

        /**
         * Gets the value of the did property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDID() {
            return did;
        }

        /**
         * Sets the value of the did property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDID(String value) {
            this.did = value;
        }

        /**
         * Gets the value of the forward property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFORWARD() {
            return forward;
        }

        /**
         * Sets the value of the forward property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFORWARD(String value) {
            this.forward = value;
        }

        /**
         * Gets the value of the accepted property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getACCEPTED() {
            return accepted;
        }

        /**
         * Sets the value of the accepted property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setACCEPTED(String value) {
            this.accepted = value;
        }

    }

}
