//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.18 at 03:16:47 PM CDT 
//


package com.ylc.authorize.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ANetApiRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ANetApiRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="merchantAuthentication" type="{AnetApi/xml/v1/schema/AnetApiSchema.xsd}merchantAuthenticationType"/>
 *         &lt;element name="refId" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ANetApiRequest", namespace = "AnetApi/xml/v1/schema/AnetApiSchema.xsd", propOrder = {
    "merchantAuthentication",
    "refId"
})
@XmlSeeAlso({
    GetUnsettledTransactionListRequest.class,
    ARBUpdateSubscriptionRequest.class,
    CreateCustomerPaymentProfileRequest.class,
    UpdateCustomerShippingAddressRequest.class,
    CreateTransactionRequest.class,
    ARBCreateSubscriptionRequest.class,
    CreateCustomerShippingAddressRequest.class,
    MobileDeviceRegistrationRequest.class,
    GetSettledBatchListRequest.class,
    GetCustomerPaymentProfileRequest.class,
    DeleteCustomerShippingAddressRequest.class,
    SendCustomerTransactionReceiptRequest.class,
    UpdateCustomerProfileRequest.class,
    GetCustomerProfileIdsRequest.class,
    CreateCustomerProfileFromTransactionRequest.class,
    GetTransactionListRequest.class,
    GetBatchStatisticsRequest.class,
    UpdateCustomerPaymentProfileRequest.class,
    CreateCustomerProfileRequest.class,
    GetCustomerShippingAddressRequest.class,
    ARBGetSubscriptionStatusRequest.class,
    GetTransactionDetailsRequest.class,
    UpdateSplitTenderGroupRequest.class,
    GetHostedProfilePageRequest.class,
    DeleteCustomerProfileRequest.class,
    ARBCancelSubscriptionRequest.class,
    LogoutRequest.class,
    DeleteCustomerPaymentProfileRequest.class,
    MobileDeviceLoginRequest.class,
    GetCustomerProfileRequest.class,
    ValidateCustomerPaymentProfileRequest.class,
    ARBGetSubscriptionListRequest.class,
    DecryptPaymentDataRequest.class,
    AuthenticateTestRequest.class,
    CreateCustomerProfileTransactionRequest.class
})
public class ANetApiRequest {

    @XmlElement(required = true)
    protected MerchantAuthenticationType merchantAuthentication;
    protected String refId;

    /**
     * Gets the value of the merchantAuthentication property.
     * 
     * @return
     *     possible object is
     *     {@link MerchantAuthenticationType }
     *     
     */
    public MerchantAuthenticationType getMerchantAuthentication() {
        return merchantAuthentication;
    }

    /**
     * Sets the value of the merchantAuthentication property.
     * 
     * @param value
     *     allowed object is
     *     {@link MerchantAuthenticationType }
     *     
     */
    public void setMerchantAuthentication(MerchantAuthenticationType value) {
        this.merchantAuthentication = value;
    }

    /**
     * Gets the value of the refId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefId() {
        return refId;
    }

    /**
     * Sets the value of the refId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefId(String value) {
        this.refId = value;
    }

}
