//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.26 at 04:41:24 PM CDT 
//


package com.ylc.peer.listaval.response.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ylc.peer.listaval.response.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ylc.peer.listaval.response.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PEER.HDR }
     * 
     */
    public PEER.HDR createPEERHDR() {
        return new PEER.HDR();
    }

    /**
     * Create an instance of {@link PEER.TRL }
     * 
     */
    public PEER.TRL createPEERTRL() {
        return new PEER.TRL();
    }

    /**
     * Create an instance of {@link PEER.RESP }
     * 
     */
    public PEER.RESP createPEERRESP() {
        return new PEER.RESP();
    }

    /**
     * Create an instance of {@link PEER.RESP.AVAILDID }
     * 
     */
    public PEER.RESP.AVAILDID createPEERRESPAVAILDID() {
        return new PEER.RESP.AVAILDID();
    }

    /**
     * Create an instance of {@link PEER }
     * 
     */
    public PEER createPEER() {
        return new PEER();
    }

}
